/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package production.management;

import classes.DBconnect;
import com.sun.glass.events.KeyEvent;
import java.text.SimpleDateFormat;
import java.sql.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author sggra
 */
public class Leaves extends javax.swing.JFrame {

    
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement ps=null;
    /**
     * Creates new form Leaves
     */
    public Leaves() {
        initComponents();
        
        con=DBconnect.getConnection();
        viewTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void viewTable(){
        
        try{
                String sql = "Select Date As Date,FNum AS Field_Number, Bags AS Bags , FWeight AS Field_Weight, FactWeight AS Factory_Weight from Leaves";
                ps = con.prepareStatement(sql);
                rs = ps.executeQuery();
                inw_table.setModel(DbUtils.resultSetToTableModel(rs));
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error in retrieving data");
        }
    }

    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        leafDate = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fNo = new javax.swing.JTextField();
        fBags = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fWeight = new javax.swing.JTextField();
        submitLeaf = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        factWeight = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        inw_table = new javax.swing.JTable();
        updateIn = new javax.swing.JButton();
        deleteIn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Date");

        jLabel2.setText("Field no");

        jLabel3.setText("Field Bags");

        fNo.setText("Enter Number");
        fNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fNoMouseClicked(evt);
            }
        });
        fNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNoActionPerformed(evt);
            }
        });
        fNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fNoKeyTyped(evt);
            }
        });

        fBags.setText("Enter number of bags");
        fBags.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fBagsMouseClicked(evt);
            }
        });
        fBags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fBagsActionPerformed(evt);
            }
        });
        fBags.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fBagsKeyTyped(evt);
            }
        });

        jLabel4.setText("Field Weight (Kgs)");

        fWeight.setText("Kgs / Bag");
        fWeight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fWeightMouseClicked(evt);
            }
        });
        fWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fWeightActionPerformed(evt);
            }
        });
        fWeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fWeightKeyTyped(evt);
            }
        });

        submitLeaf.setText("Submit");
        submitLeaf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitLeafActionPerformed(evt);
            }
        });

        jLabel5.setText("Factory Weight (Kgs)");

        factWeight.setText("Kgs");
        factWeight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                factWeightMouseClicked(evt);
            }
        });
        factWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factWeightActionPerformed(evt);
            }
        });
        factWeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                factWeightKeyTyped(evt);
            }
        });

        inw_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Date", "Field No", "Field bags", "Field weight", "Factory weight"
            }
        ));
        inw_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inw_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(inw_table);

        updateIn.setText("Update");
        updateIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateInActionPerformed(evt);
            }
        });

        deleteIn.setText("Delete");
        deleteIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteInActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGap(216, 216, 216)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fBags, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fNo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(leafDate, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(factWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(deleteIn)
                            .addGap(18, 18, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(submitLeaf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, Short.MAX_VALUE)
                            .addComponent(updateIn))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(leafDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(fNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(fBags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(fWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(factWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(deleteIn)
                        .addComponent(submitLeaf))
                    .addComponent(updateIn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Inward", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(493, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNoActionPerformed

    private void fWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fWeightActionPerformed

    private void factWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_factWeightActionPerformed

    private void submitLeafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitLeafActionPerformed
       DateFormat formatted = new SimpleDateFormat("YYYY-MM-dd");
        int fieldNo = Integer.parseInt(fNo.getText());
        String bags = fBags.getText();
        String Sdate = formatted.format(leafDate.getDate());
        //Date Sdate = (Date) teaSuppDate.getDate();
        double fieldW = Double.parseDouble(fWeight.getText());
        double facWeight = Double.parseDouble(factWeight.getText());
        int rowno = inw_table.getSelectedRow();
            //DBconnect conn = new DBconnect();
            System.out.println(fieldNo);
            System.out.println(bags);
            System.out.println(Sdate);
            System.out.println(fieldW);
            System.out.println(facWeight);
                  
            
            
        try{
            String sql = "insert into Leaves(Date,FNum,Bags,FWeight,FactWeight) values('"+Sdate+"','"+fieldNo+"','"+bags+"','"+fieldW+"','"+facWeight+"')";
           
            
            
            ps=con.prepareStatement(sql);
            ps.execute();
            
            JOptionPane.showMessageDialog(null,"Data Added");
            viewTable();
            
            fNo.setText("Enter Number");
            fBags.setText("Enter Number of Bags");
            leafDate.setDate(null);
            fWeight.setText("Kgs / Bag");
            factWeight.setText("Kgs");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
            System.out.println("error in submit "+ e);
        }
        
        // TODO add your handling code here:
                
        
      
    }//GEN-LAST:event_submitLeafActionPerformed

    private void fBagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fBagsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fBagsActionPerformed

    private void updateInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateInActionPerformed
        DateFormat formatted = new SimpleDateFormat("YYYY-MM-dd");
        int fieldNo = Integer.parseInt(fNo.getText());
        String bags = fBags.getText();
        String Sdate = formatted.format(leafDate.getDate());
        //Date Sdate = (Date) teaSuppDate.getDate();
        double fieldW = Double.parseDouble(fWeight.getText());
        double facWeight = Double.parseDouble(factWeight.getText());
        int rowno = inw_table.getSelectedRow();
            //DBconnect conn = new DBconnect();
            System.out.println(fieldNo);
            System.out.println(bags);
            System.out.println(Sdate);
            System.out.println(fieldW);
            System.out.println(facWeight);
                  
            
            
        try{
            String sql = "Update Leaves set Date='"+Sdate+"',Bags = '"+bags+"',FWeight = '"+fieldW+"',FactWeight = '"+facWeight+"' where FNum='"+fieldNo+"'";
           
            
            
            ps=con.prepareStatement(sql);
            ps.execute();
            
            JOptionPane.showMessageDialog(null,"Data Updated");
            viewTable();
            
            fNo.setText("Enter Number");
            fBags.setText("Enter Number of Bags");
            leafDate.setDate(null);
            fWeight.setText("Kgs / Bag");
            factWeight.setText("Kgs");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
            System.out.println("error in Update "+ e);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_updateInActionPerformed

    private void deleteInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteInActionPerformed
        //DateFormat formatted = new SimpleDateFormat("YYYY-MM-dd");
        int fieldNo = Integer.parseInt(fNo.getText());
        //String bags = fBags.getText();
        //String Sdate = formatted.format(leafDate.getDate());
        //Date Sdate = (Date) teaSuppDate.getDate();
        //double fieldW = Double.parseDouble(fWeight.getText());
        //double facWeight = Double.parseDouble(factWeight.getText());
        int rowno = inw_table.getSelectedRow();
            //DBconnect conn = new DBconnect();
            System.out.println(fieldNo);
          //  System.out.println(bags);
           // System.out.println(Sdate);
            //System.out.println(fieldW);
            //System.out.println(facWeight);
                  
            
            
        try{
            String sql = "Delete from Leaves where FNum='"+fieldNo+"'";
           
            
            
            ps=con.prepareStatement(sql);
            ps.execute();
            
            JOptionPane.showMessageDialog(null,"Data Deleted");
            viewTable();
            
            fNo.setText("Enter Number");
            fBags.setText("Enter Number of Bags");
            leafDate.setDate(null);
            fWeight.setText("Kgs / Bag");
            factWeight.setText("Kgs");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
            System.out.println("error in Delete "+ e);
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_deleteInActionPerformed

    private void fNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fNoMouseClicked
        fNo.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_fNoMouseClicked

    private void fBagsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fBagsMouseClicked
      fBags.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_fBagsMouseClicked

    private void fWeightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fWeightMouseClicked
        fWeight.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_fWeightMouseClicked

    private void factWeightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_factWeightMouseClicked
        factWeight.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_factWeightMouseClicked

    private void inw_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inw_tableMouseClicked
        int rowNo = inw_table.getSelectedRow();
        
        fNo.setText(inw_table.getValueAt(rowNo,1).toString());
        fNo.disable();
        
        submitLeaf.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_inw_tableMouseClicked

    private void fNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fNoKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_DELETE)){
        getToolkit().beep();
        evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_fNoKeyTyped

    private void fBagsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fBagsKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_DELETE)){
        getToolkit().beep();
        evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_fBagsKeyTyped

    private void fWeightKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fWeightKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_DELETE)){
        getToolkit().beep();
        evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_fWeightKeyTyped

    private void factWeightKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_factWeightKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_DELETE)){
        getToolkit().beep();
        evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_factWeightKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         FunctionUIn fui = new FunctionUIn();
        fui.setVisible(true);
        setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Leaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Leaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Leaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Leaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Leaves().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteIn;
    private javax.swing.JTextField fBags;
    private javax.swing.JTextField fNo;
    private javax.swing.JTextField fWeight;
    private javax.swing.JTextField factWeight;
    private javax.swing.JTable inw_table;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.toedter.calendar.JDateChooser leafDate;
    private javax.swing.JButton submitLeaf;
    private javax.swing.JButton updateIn;
    // End of variables declaration//GEN-END:variables
}
