/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package production.management;

import classes.DBconnect;
import com.sun.glass.events.KeyEvent;
import java.text.SimpleDateFormat;
import java.sql.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author sggra
 */
public class TeaQualityManagement extends javax.swing.JFrame {

    
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement ps=null;
    //Date date = new Date();
    
    /**
     * Creates new form TeaQualityManagement
     */
    public TeaQualityManagement() {
        initComponents();
        
        con=DBconnect.getConnection();
        viewTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        supplierID = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        submitTLC = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        pricePKg = new javax.swing.JTextField();
        updateTLC = new javax.swing.JButton();
        deleteTLC = new javax.swing.JButton();
        teaSuppDate = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        cID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tLC_table = new javax.swing.JTable();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(100, 50));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(477, 500));

        jLabel5.setText("Supplier ID");

        jLabel6.setText("Date");

        jLabel7.setText("Tea leaves quantity");

        supplierID.setText("Enter ID");
        supplierID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplierIDMouseClicked(evt);
            }
        });
        supplierID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierIDActionPerformed(evt);
            }
        });

        quantity.setText("Kgs");
        quantity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quantityMouseClicked(evt);
            }
        });
        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });
        quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                quantityKeyTyped(evt);
            }
        });

        submitTLC.setText("Submit");
        submitTLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitTLCActionPerformed(evt);
            }
        });

        jLabel8.setText("Tea price per Kg");

        pricePKg.setText("Price/Kg");
        pricePKg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pricePKgMouseClicked(evt);
            }
        });
        pricePKg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pricePKgKeyTyped(evt);
            }
        });

        updateTLC.setText("Update");
        updateTLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTLCActionPerformed(evt);
            }
        });

        deleteTLC.setText("Delete");
        deleteTLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTLCActionPerformed(evt);
            }
        });

        jLabel9.setText("Collection ID");

        cID.setText("Enter ID");
        cID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cIDMouseClicked(evt);
            }
        });
        cID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cIDActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(deleteTLC)
                                .addGap(84, 84, 84)
                                .addComponent(submitTLC)
                                .addGap(65, 65, 65)
                                .addComponent(updateTLC))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(151, 151, 151)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cID, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(supplierID, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(teaSuppDate, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pricePKg, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 732, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(supplierID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(teaSuppDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pricePKg)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteTLC)
                    .addComponent(submitTLC)
                    .addComponent(updateTLC))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        tLC_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tLC_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tLC_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tLC_table);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Tea leaves Collection", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewTable(){
        
        try{
                String sql = "Select * from teacollection";
                ps = con.prepareStatement(sql);
                rs = ps.executeQuery();
                tLC_table.setModel(DbUtils.resultSetToTableModel(rs));
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error in retrieving data");
        }
    }
    
    private void submitTLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitTLCActionPerformed
        DateFormat formatted = new SimpleDateFormat("YYYY-MM-dd");
        int collID = Integer.parseInt(cID.getText());
        String suppID = supplierID.getText();
        String Sdate = formatted.format(teaSuppDate.getDate());
        //Date Sdate = (Date) teaSuppDate.getDate();
        double quant = Double.parseDouble(quantity.getText());
        double pPKg = Double.parseDouble(pricePKg.getText());
        int rowno = tLC_table.getSelectedRow();
            //DBconnect conn = new DBconnect();
            System.out.println(cID);
            System.out.println(suppID);
            System.out.println(Sdate);
            System.out.println(quant);
            System.out.println(pPKg);
            
            
            
        try{
            String sql = "insert into teacollection(collID,SuppID,DateAM,Quantity,Price) values('"+collID+"','"+suppID+"','"+Sdate+"','"+quant+"','"+pPKg+"')";
            //String sql="insert into teacollection values('125','123','123','123');";
            //PreparedStatement pst = conn.prepareStatement(sql);
            
           // pst.setString(1,supplierID.getText());
            //pst.setString(2,Sdate);
           // pst.setString(3,supplierID.getText());
           // pst.setString(4,supplierID.getText());
            
            //ResultSet rs = pst.executeQuery(sql);
            
            
            
            ps=con.prepareStatement(sql);
            ps.execute();
            
            JOptionPane.showMessageDialog(null,"Data Added");
            viewTable();
            
            cID.setText("Enter ID");
            supplierID.setText("Enter ID");
            teaSuppDate.setDate(null);
            quantity.setText("Kgs");
            pricePKg.setText("Price/Kg");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
            System.out.println("error in submit "+ e);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_submitTLCActionPerformed

    private void supplierIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierIDActionPerformed
    
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierIDActionPerformed

    private void updateTLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTLCActionPerformed
        DateFormat formatted = new SimpleDateFormat("YYYY-MM-dd");
        int collID = Integer.parseInt(cID.getText());
        String suppID = supplierID.getText();
        String Sdate = formatted.format(teaSuppDate.getDate());
        //Date Sdate = (Date) teaSuppDate.getDate();
        double quant = Double.parseDouble(quantity.getText());
        double pPKg = Double.parseDouble(pricePKg.getText());
        int rowno = tLC_table.getSelectedRow();
            //DBconnect conn = new DBconnect();
            System.out.println(cID);
            System.out.println(suppID);
            System.out.println(Sdate);
            System.out.println(quant);
            System.out.println(pPKg);
            
            
            
        try{
            String sql = "update teacollection set DateAM = '"+Sdate+"',Quantity = '"+quant+"',Price = '"+pPKg+"' where collID = '"+collID+"' AND SuppID = '"+suppID+"'";
            //String sql="insert into teacollection values('125','123','123','123');";
            //PreparedStatement pst = conn.prepareStatement(sql);
            
           // pst.setString(1,supplierID.getText());
            //pst.setString(2,Sdate);
           // pst.setString(3,supplierID.getText());
           // pst.setString(4,supplierID.getText());
            
            //ResultSet rs = pst.executeQuery(sql);
            
            
            
            ps=con.prepareStatement(sql);
            ps.execute();
            
            JOptionPane.showMessageDialog(null,"Update Succesfull");
            viewTable();
            
            cID.setText("Enter ID");
            supplierID.setText("Enter ID");
            teaSuppDate.setDate(null);
            quantity.setText("Kgs");
            pricePKg.setText("Price/Kg");
            submitTLC.setVisible(true);
            cID.enable();
            supplierID.enable();
        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
            System.out.println("error in update "+ e);
        }

         
        
        // TODO add your handling code here:
    }//GEN-LAST:event_updateTLCActionPerformed

    private void deleteTLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTLCActionPerformed
        //DateFormat formatted = new SimpleDateFormat("YYYY-MM-dd");
        int collID = Integer.parseInt(cID.getText());
        //String suppID = supplierID.getText();
        //String Sdate = formatted.format(teaSuppDate.getDate());
        //Date Sdate = (Date) teaSuppDate.getDate();
        //double quant = Double.parseDouble(quantity.getText());
        //double pPKg = Double.parseDouble(pricePKg.getText());
        int rowno = tLC_table.getSelectedRow();
            //DBconnect conn = new DBconnect();
            System.out.println(cID);
            //System.out.println(suppID);
            //System.out.println(Sdate);
            //System.out.println(quant);
            //System.out.println(pPKg);
            
            
            
        try{
            String sql = "delete from teacollection where collID = '"+collID+"'";
            //String sql="insert into teacollection values('125','123','123','123');";
            //PreparedStatement pst = conn.prepareStatement(sql);
            
           // pst.setString(1,supplierID.getText());
            //pst.setString(2,Sdate);
           // pst.setString(3,supplierID.getText());
           // pst.setString(4,supplierID.getText());
            
            //ResultSet rs = pst.executeQuery(sql);
            
            
            
            ps=con.prepareStatement(sql);
            ps.execute();
            
            JOptionPane.showMessageDialog(null,"Delete Succesfull");
            viewTable();
            
            cID.setText("Enter ID");
            supplierID.setText("Enter ID");
            teaSuppDate.setDate(null);
            quantity.setText("Kgs");
            pricePKg.setText("Price/Kg");
            submitTLC.setVisible(true);
            cID.enable();
            supplierID.enable();
        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
            System.out.println("error in delete "+ e);
        }

        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteTLCActionPerformed

    private void supplierIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierIDMouseClicked
        supplierID.setText("");
    }//GEN-LAST:event_supplierIDMouseClicked

    private void tLC_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tLC_tableMouseClicked
        int rowNo = tLC_table.getSelectedRow();
        
        cID.setText(tLC_table.getValueAt(rowNo, 0).toString());
        supplierID.setText(tLC_table.getValueAt(rowNo, 1).toString());
        
           submitTLC.setVisible(false);
           cID.disable();
           supplierID.disable();
        // TODO add your handling code here:
    }//GEN-LAST:event_tLC_tableMouseClicked

    private void cIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cIDActionPerformed

    private void cIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cIDMouseClicked
           cID.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_cIDMouseClicked

    private void quantityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quantityMouseClicked
           quantity.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityMouseClicked

    private void pricePKgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pricePKgMouseClicked
            pricePKg.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_pricePKgMouseClicked

    private void quantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityKeyTyped
        
    char c = evt.getKeyChar();
    if(!(Character.isDigit(c) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_DELETE)){
      getToolkit().beep();
      evt.consume();
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityKeyTyped

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void pricePKgKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pricePKgKeyTyped
                
        
        


        // TODO add your handling code here:
    }//GEN-LAST:event_pricePKgKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         FunctionUIn fui = new FunctionUIn();
        fui.setVisible(true);
        setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeaQualityManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeaQualityManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeaQualityManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeaQualityManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeaQualityManagement().setVisible(true);
            }
        });
    }
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cID;
    private javax.swing.JButton deleteTLC;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField pricePKg;
    private javax.swing.JTextField quantity;
    private javax.swing.JButton submitTLC;
    private javax.swing.JTextField supplierID;
    private javax.swing.JTable tLC_table;
    private com.toedter.calendar.JDateChooser teaSuppDate;
    private javax.swing.JButton updateTLC;
    // End of variables declaration//GEN-END:variables
}
